# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sliceSamplerRcpp <- function(sampMat, samp, chol, lth, uth) {
    invisible(.Call('_selectiveROI_sliceSamplerRcpp', PACKAGE = 'selectiveROI', sampMat, samp, chol, lth, uth))
}

sampleUnivTruncNorm <- function(mu, sd, lower, upper) {
    .Call('_selectiveROI_sampleUnivTruncNorm', PACKAGE = 'selectiveROI', mu, sd, lower, upper)
}

sampleTruncNorm <- function(sample, lower, upper, mean, precision, cycles) {
    .Call('_selectiveROI_sampleTruncNorm', PACKAGE = 'selectiveROI', sample, lower, upper, mean, precision, cycles)
}

